name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '20'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
