name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clear npm cache
        run: npm cache clean --force  # Clear npm cache

      - name: Install dependencies
        run: npm install --omit=optional  # Use --omit=optional to skip optional dependencies

      - name: Run tests
        run: npm test
